name: juju-region-no-flag
version: 2.0-rc1
summary: juju client
description: Through the use of charms, juju provides you with shareable, re-usable, and repeatable expressions of devops best practices.
confinement: devmode

apps:
  juju:
    command: bin/juju
    plugs: [network, network-bind, home]

parts:
  juju:
    plugin: godeps
    go-importpath: github.com/juju/juju
    source: https://github.com/reedobrien/juju.git
    source-type: git
    #If you want to grab a specific revision tag, include it here
    #source-tag: juju-2.0-beta18
    source-branch: feature/region-flag-model-defaults
    snap:
    - bin/juju
    - bin/jujud 
    - -bin/filetoconst
    - -bin/winuserdata
    #If you are releasing a build with public streams, also remove the agent
    
